# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-09 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('question', models.TextField(max_length=255)),
                ('status', models.TextField(max_length=255)),
                ('runtime', models.TextField(max_length=255)),
                ('qid', models.IntegerField(default=0)),
                ('category', models.TextField(max_length=255)),
            ],
        ),
    ]
