# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-09 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissions',
            name='code',
            field=models.TextField(default='null'),
        ),
        migrations.AddField(
            model_name='submissions',
            name='metrics',
            field=models.TextField(default='null'),
        ),
        migrations.AddField(
            model_name='submissions',
            name='quality',
            field=models.TextField(default='null'),
        ),
    ]
