# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-09 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('user', models.TextField(max_length=255, primary_key=True, serialize=False)),
                ('easy', models.IntegerField(default=0)),
                ('medium', models.IntegerField(default=0)),
                ('hard', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=1500)),
                ('rank', models.IntegerField(default=-1)),
            ],
        ),
    ]
